[build]
publish = "site/"
command = """
sudo apt install software-properties-common -y &&
sudo add-apt-repository ppa:deadsnakes/ppa &&
sudo apt install python3.10 &&
sudo apt install python3.10-venv &&
python3.10 -m venv venv &&
source venv/bin/activate &&
curl -sSL https://install.python-poetry.org | python3.10 - &&
poetry install &&
prima build
"""
