[build]
publish = "site/"
command = """
apt install software-properties-common -y &&
add-apt-repository ppa:deadsnakes/ppa &&
apt install python3.10 &&
apt install python3.10-venv &&
python3.10 -m venv venv &&
source venv/bin/activate &&
curl -sSL https://install.python-poetry.org | python3.10 - &&
poetry install &&
prima build
"""
