backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  
media_folder: "/assets/media"
public_folder: "/assets/media"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "lezioni" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Lezioni (IT)" # Used in the UI
    identifier_field: lezioni
    folder: "it/lezioni" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Lezione", name: "lezioni", widget: "string"}
      - label: "Livello"
        name: "livello"
        required: false
        widget: "list"
        allow_add: true
      - {label: "Settimana", name: "settimana", widget: "string", required: false}
      - {label: "Contenuto grammaticale", name: "contenuto-grammaticale", widget: "string", required: false}
      - {label: "Prerequisiti", name: "prerequisiti", widget: "string", required: false}
      - {label: "Testo", name: "body", widget: "markdown", required: false}
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        required: false
        default: "/assets/img/default.png"
        media_library:
          config:
            multiple: true
      - {label: "Incorporamento video", name: "video_embed", widget: "string", required: false}
      - label: "English Version"
        name: "lesson"
        required: false
        widget: "relation"
        collection: "lessons"
        search_fields: ["lesson"]
        value_field: "lesson"
        display_fields: ["lesson"]
      - label: "Fair Use File"
        name: "fair-use"
        widget: "file"
        required: false
  - name: "lessons" # Used in routes, e.g., /admin/collections/blog
    label: "Lesson (EN)" # Used in the UI
    editor:
      preview: false
    identifier_field: lesson
    folder: "en/lessons" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Lesson Name"
        name: "lesson"
        widget: "string"

      - label: "Medium / Media Type"
        name: "medium"
        widget: "list"
        required: false
        allow_add: true

      - label: "Practice"
        name: "practice"
        required: false
        widget: "list"
        allow_add: true

      - label: "Learning Outcome"
        name: "learning_outcome"
        required: false
        widget: "list"
        allow_add: true

      - label: "Level"
        name: "level"
        required: false
        widget: "list"
        allow_add: true
      - {label: "Week", name: "week", widget: "string", required: false}
      - label: "Citation Information"
        name: citation_information
        widget: markdown
      - {label: "Prerequisites", name: "prerequisites", widget: "string", required: false}
      - {label: "Text", name: "body", widget: "markdown", required: false}
      - label: "Featured Image" 
        name: "thumbnail"
        widget: "image"
        choose_url: true
        required: false
        default: "/assets/img/default.png"
        media_library:
          config:
            multiple: true
      - {label: "Video Embed", name: "video_embed", widget: "string", required: false}
      - {label: "Video Embed Subtitles", name: "video_embed_subtitles", widget: "string", required: false}
      - label: "Italian Version"
        name: "lezioni"
        required: false
        widget: "relation"
        collection: "lezioni"
        search_fields: ["lezioni"]
        value_field: "lezioni"
        display_fields: ["lezioni"]
      - label: "Fair Use File"
        name: "fair-use"
        widget: "file"
        required: false

  - label: "Items"
    name: "lesson_items"

    editor:
      preview: false
    files:
      - label: "Items (EN)"
        name: "items-en"
        file: "_data/en_items.yaml"
        fields:
          - label: Items
            name: items
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: markdown
                required: false
              - label: "Related Lesson"
                name: "lesson"
                required: false
                widget: "relation"
                collection: "lessons"
                search_fields: ["lesson"]
                value_field: "lesson"
                display_fields: ["lesson"]
              - label: "PDF File"
                name: "pdf_file"
                widget: "file"
                required: false
              - label: "DOC File"
                name: "doc_file"
                widget: "file"
                required: false
              - label: "HTML File"
                name: "html_file"
                widget: "file"
                required: false

      - label: "Items (IT)"
        name: "items-it"
        file: "_data/it_items.yaml"
        fields:
          - label: Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - label: Title
                name: title
                widget: string
              - label: "Related Lesson"
                name: "lesson"
                required: false
                widget: "relation"
                collection: "lessons"
                search_fields: ["lesson"]
                value_field: "lesson"
                display_fields: ["lesson"]
              - label: "PDF File"
                name: "pdf_file"
                widget: "file"
                required: false
              - label: "DOC File"
                name: "doc_file"
                widget: "file"
                required: false
              - label: "HTML File"
                name: "html_file"
                widget: "file"
                required: false
              - label: "Solution"
                name: "solution"
                widget: "file"
                required: false

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - name: "about-en"
        label: "About (EN)"
        file: "/en/about.md"
        fields:
          - { label: Title, name: text, widget: string }
          - {label: "Text", name: "body", widget: "markdown", required: false}

      - name: "informazioni-it"
        label: "Informazioni (IT)"
        file: "/it/informazioni.md"
        fields:
          - { label: Titolo, name: text, widget: string }
          - {label: "Text", name: "body", widget: "markdown", required: false}
  
  - label: "Landing Page Video"
    name: "landing-video"
    editor:
      preview: false
    files:
      - label: "Videos"
        name: "videos"
        file: "_data/videos.yaml"
        fields:
          - label: files
            name: files
            widget: list
            allow_add: true
            collapsed: false
            fields:
              - label: Title
                name: title
                widget: string
              - label: Alt text
                name: alt-text
                widget: string
              - label: "Video URL"
                name: "video_url"
                widget: string
                required: false