backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "prima/assets/media"

collections:
  - name: "lessons" # Used in routes, e.g., /admin/collections/blog
    label: "Lesson" # Used in the UI
    identifier_field: clip
    folder: "prima/content/lessons" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Clip", name: "clip", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Level", name: "level", widget: "string"}
      - {label: "Video", name: "video", widget: "string"}
      - {label: "Week", name: "week", widget: "string"}
      - {label: "Grammar content", name: "grammar-content", widget: "string"}
      - {label: "Prerequisites", name: "prerequisites", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    folder: "prima/content/pages"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "authro", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}